### ISSUE TITLE
Possible to show a loading gif on successful submission?

### ISSUE THREAD

**Issue by melinazell** [zaneray/scrupulous#6]
Hi,
More of a usability request... is it possible to add a (any) loading gif image on successful form validation and click on the submit button?

**Comment by ajdinstel** [comment]
Hi melinazell, the mechanism we built into Scrupulous to allow for things like this are the 'valid' and 'invalid' callback methods.  If I understand your request correctly, you could try something like this to do custom actions when your form either passes or fails your front-end validation rules:

    $('#your-form-identifier').scrupulous({
        valid: function(){
            $('.loading-gif-image').show();  // or some similar method for presenting your gif
            return true;    // return true here otherwise form submission will not continue.
        },
        invalid: function(){
            $('.custom-fail-message').show();  // or some other custom action
            return false;   // this will cause browser to bail on form submission
        }
    });

A pointer for using the callback methods: try to only bind Scrupulous to any form once.  If you accidentally bind Scrupulous to a form multiple times, only the first instance will run.  For instance, if you do the following, your custom callback methods will never run on '#custom-form".  Good luck!

    $('.class-name-on-all-forms').scrupulous();   // generically apply validation to all your forms

    $('#custom-form').scrupulous({
        valid: function(){
            customValidAction();    // this will never run
       },
       invalid: function(){
           customInvalidAction();    // this will never run
       }
    });
